### ISSUE TITLE
Kali(attacker vm)'s browser hang after running for a short while.

### ISSUE THREAD

**Issue by LiuYuancheng** [brant-ruan/training-ncl-aptx4869#1]
I guess we may need to give a higher OpenStack flavor to the attacker vm (such m1.medium/large). Current when we use the attacker kali vm to access the DVWA web server and upload the php-webshell script to the vicim-01(10.1.26.9), after a very shot time, the browser will get no responding as shown below (The page will change to black color)
![firefox_not_responding_2](https://user-images.githubusercontent.com/26474823/196073238-9ba892d9-5fe1-4db1-91df-d26aadf4075d.png)

And after a while will pop-up a error message:
![firefox_not_responding_3](https://user-images.githubusercontent.com/26474823/196073964-7d212a59-5132-4a2f-99cd-0223ebde791b.png)

I guess this may because the flavor _csirtmu.tiny1x2_ is not enough to support the kali system run Firefox smoothly.

**Comment by brant-ruan** [comment]
Sure, I will try to enlarge it.
